name: Go Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  RUN_INTEGRATION_TESTS: "true"  # Глобальная переменная для всех шагов

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true

    - name: Run unit tests
      run: |
        cd api
        go test -v -short ./...

    - name: Run integration tests
      if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
      run: |
        cd api
        go test -v -run TestGetStopData_RealAPI
      env:
        API_BASE_URL: "https://api.moscowapp.mos.ru/v8.2/"
        # Добавьте другие необходимые переменные окружения

    - name: Build example
      run: |
        cd example
        go build